### ISSUE TITLE
[feature] How to build a single tutorial?

### ISSUE THREAD

**Issue by prabhuomkar** [prabhuomkar/pytorch-cpp#66]
@mfl28 can we add some instructions on how to build a single tutorial and if necessary its datasets only?
I believe many users want to try "X" tutorial from all and if there is an easy to follow guide that would be great :)

PS: Added this as an issue for visibility and referencing.

**Comment by mfl28** [comment]
There is no easy way to do this currently because the datasets are downloaded at CMake configure time. At this stage we do not yet know which target the user wants to build. 

I have been thinking about instead doing the datasets pulling as post-build steps with dependencies on the specific tutorials that need them. So for example for the image captioning tutorial (that needs the flickr8k dataset) it should work like this:
1. Configure/Generate step: `cmake -B build ...`: No datasets are downloaded.
2. Build step: `cmake --build build --target image-captioning`: Builds only the image-captioning tutorial (and dependencies). After the build only the flickr8k dataset is downloaded (if it wasn't already).

I think this would be a better way than how it currently works and I can do a PR sometime later... We can discuss possible problems that might arise with this here.
What's your take on this?

**Comment by prabhuomkar** [comment]
- We can download all sets of datasets on start, but I think a better way would be to add it as a dependency for individual tutorials while building. After building a tutorial, dataset availability will be checked and downloaded if not exists
- I think we support build all tutorials, we should have both options: Build all / Build single, by specifying the target as you mentioned. We can go with this, if we solve the dataset complexity.
